sudo: false
cache:
  directories:
    - $HOME/.m2

language: java
script: "mvn verify"
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
after_success:
  - mvn clean test jacoco:report coveralls:report
